# -*- coding: utf-8 -*-
"""Covid19 Data Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NdTA0zLjKbZtPFFPOw-n76E-cIlOybub
"""

!pip install plotly requests

import pandas as pd
import requests
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# Fetch global COVID data
url_global = "https://disease.sh/v3/covid-19/all"
global_data = requests.get(url_global).json()

# Fetch country-wise data
url_countries = "https://disease.sh/v3/covid-19/countries"
countries_data = requests.get(url_countries).json()

# Convert to DataFrame
df = pd.DataFrame(countries_data)

# Display first 5 rows
df.head()

# Select important columns
df = df[['country', 'cases', 'todayCases', 'deaths',
         'todayDeaths', 'recovered', 'active',
         'critical', 'tests', 'population']]

# Sort by total cases
df = df.sort_values(by='cases', ascending=False)

df.head()

top10 = df.head(10)
plt.figure(figsize=(8, 6))
sns.barplot(x='country', y='cases', data=top10)
fig = px.bar(top10,
             x='country',
             y='cases',
             title='Top 10 Countries by Total COVID Cases',
             color='cases',
             text='cases')

plt.show()

plt.figure(figsize=(8, 6))
sns.barplot(x='country', y='deaths', data=top10)
plt.show() # Display the seaborn plot

fig_cases_deaths = px.scatter(df,
                 x='cases',
                 y='deaths',
                 size='recovered',
                 color='country',
                 hover_name='country',
                 title='Cases vs Deaths (Bubble Size = Recovered)')
fig_cases_deaths.show() # Display the plotly scatter plot

fig_active_critical = px.bar(df.head(10),
             x='country',
             y=['active', 'critical'],
             barmode='group',
             title='Active vs Critical Cases (Top 10 Countries)')

fig_active_critical.show()

# Removed seaborn barplot to avoid plt conflict and redundant plotting

plt.figure(figsize=(8, 6))
sns.barplot(x='country', y='tests', data=top10)
plt.show() # Display the seaborn plot

fig_map = px.choropleth(df,
                    locations="country",
                    locationmode="country names",
                    color="cases",
                    hover_name="country",
                    color_continuous_scale="Reds",
                    title="Worldwide COVID-19 Cases Map")
fig_map.show() # Display the plotly map

url_vaccine = "https://disease.sh/v3/covid-19/vaccine/coverage/countries?lastdays=1"
vaccine_data = requests.get(url_vaccine).json()

# Convert to DataFrame
vaccine_list = []

for country in vaccine_data:
    vaccine_list.append({
        "country": country['country'],
        "vaccinations": list(country['timeline'].values())[0]
    })

vaccine_df = pd.DataFrame(vaccine_list)

vaccine_df.head()

top_vaccine = vaccine_df.sort_values(by="vaccinations", ascending=False).head(10)
plt.figure(figsize=(8, 6))
sns.barplot(x="country", y="vaccinations", data=top_vaccine)
plt = px.bar(top_vaccine,
             x="country",
             y="vaccinations",
             title="Top 10 Countries by Vaccinations",
             color="vaccinations")

plt.show()

country_name = input("Enter Country Name: ")

country_data = df[df['country'].str.lower() == country_name.lower()]

if not country_data.empty:
    print(country_data)
else:
    print("Country not found!")

print("🌍 Global COVID-19 Summary")
print("Total Cases:", global_data['cases'])
print("Total Deaths:", global_data['deaths'])
print("Total Recovered:", global_data['recovered'])
print("Total Active:", global_data['active'])

